### ISSUE TITLE
React warnings in the javascript console

### ISSUE THREAD

**Issue by joker-777** [luffy84217/react-input-pin-code#70]
**Describe the bug**
We see a couple of warnings in the JavaScript console when using this library.

**Package Version**
react-input-pin-code: "npm:^1.2.0"
react: "npm:^18.2.0"
react-dom: "npm:^18.2.0"

**Screenshots**
![Screenshot_20231025_124246](https://github.com/luffy84217/react-input-pin-code/assets/378859/2c656a11-5e2a-4608-abf1-534badb52b3c)

**Comment by luffy84217** [comment]
@joker-777 you might pass props down to children components, and ultimately to a DOM element.

here is the related issue: https://stackoverflow.com/questions/54468535/how-to-solve-warning-react-does-not-recognize-the-x-prop-on-a-dom-element
related documentation: https://reactjs.org/warnings/unknown-prop.html

see if it works for you

**Comment by luffy84217** [comment]
@joker-777 Hi sorry for late response, it seems that `styled-components` has updated to v6, so the input component is needed updated to compatible with
If you need a quick solution in condition, you could downgrade styled-components to v5.
Also, glad to see you PR to make it compatible with styled-components v6.
